# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\AcousticTools\Working\AcousticToolsUpdated2_bandwidthALT.ui'
#
# Created: Tue Aug 04 15:28:49 2015
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1012, 639)
        self.gridLayout_7 = QtGui.QGridLayout(Form)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tabWidget = QtGui.QTabWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(994, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tab)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_13 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.calculateTSButton = QtGui.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.calculateTSButton.setFont(font)
        self.calculateTSButton.setObjectName(_fromUtf8("calculateTSButton"))
        self.gridLayout_13.addWidget(self.calculateTSButton, 0, 0, 1, 1)
        self.saveFigButton = QtGui.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.saveFigButton.setFont(font)
        self.saveFigButton.setObjectName(_fromUtf8("saveFigButton"))
        self.gridLayout_13.addWidget(self.saveFigButton, 0, 2, 1, 1)
        self.exportDataButton = QtGui.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.exportDataButton.setFont(font)
        self.exportDataButton.setObjectName(_fromUtf8("exportDataButton"))
        self.gridLayout_13.addWidget(self.exportDataButton, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.frame_2, 1, 0, 1, 2)
        self.TSCurveFigure = mplwidget(self.tab)
        self.TSCurveFigure.setObjectName(_fromUtf8("TSCurveFigure"))
        self.gridLayout_12.addWidget(self.TSCurveFigure, 0, 1, 1, 1)
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.maxFreq = QtGui.QDoubleSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.maxFreq.setFont(font)
        self.maxFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxFreq.setDecimals(1)
        self.maxFreq.setMaximum(800.0)
        self.maxFreq.setSingleStep(0.1)
        self.maxFreq.setObjectName(_fromUtf8("maxFreq"))
        self.gridLayout.addWidget(self.maxFreq, 15, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 15, 6, 1, 1)
        self.label_15 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 8, 0, 1, 4)
        self.label_14 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 7, 0, 1, 2)
        self.targetDiameter = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.targetDiameter.setFont(font)
        self.targetDiameter.setObjectName(_fromUtf8("targetDiameter"))
        self.gridLayout.addWidget(self.targetDiameter, 7, 2, 1, 4)
        self.targetDensity = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.targetDensity.setFont(font)
        self.targetDensity.setObjectName(_fromUtf8("targetDensity"))
        self.gridLayout.addWidget(self.targetDensity, 6, 2, 1, 4)
        self.label_2 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.waterDensity = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.waterDensity.setFont(font)
        self.waterDensity.setObjectName(_fromUtf8("waterDensity"))
        self.gridLayout.addWidget(self.waterDensity, 1, 2, 1, 4)
        self.targetMaterial = QtGui.QComboBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.targetMaterial.setFont(font)
        self.targetMaterial.setObjectName(_fromUtf8("targetMaterial"))
        self.targetMaterial.addItem(_fromUtf8(""))
        self.targetMaterial.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.targetMaterial, 5, 2, 1, 3)
        self.soundSpeed = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.soundSpeed.setFont(font)
        self.soundSpeed.setObjectName(_fromUtf8("soundSpeed"))
        self.gridLayout.addWidget(self.soundSpeed, 2, 2, 1, 3)
        self.tranSoundSpeed = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tranSoundSpeed.setFont(font)
        self.tranSoundSpeed.setObjectName(_fromUtf8("tranSoundSpeed"))
        self.gridLayout.addWidget(self.tranSoundSpeed, 10, 2, 1, 4)
        self.line_4 = QtGui.QFrame(self.frame)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 11, 0, 1, 9)
        self.label_17 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 10, 0, 1, 2)
        self.label_16 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 9, 0, 1, 2)
        self.label_12 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 2)
        self.label_13 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 6, 0, 1, 2)
        self.longSoundSpeed = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.longSoundSpeed.setFont(font)
        self.longSoundSpeed.setObjectName(_fromUtf8("longSoundSpeed"))
        self.gridLayout.addWidget(self.longSoundSpeed, 9, 2, 1, 4)
        self.label_3 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.line = QtGui.QFrame(self.frame)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 3, 0, 1, 9)
        self.label_5 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 15, 4, 1, 1)
        self.label_21 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 10, 6, 1, 1)
        self.label_20 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 9, 6, 1, 1)
        self.label_19 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 7, 6, 1, 1)
        self.label_18 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 6, 6, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 6, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 6, 1, 1)
        self.minFreq = QtGui.QDoubleSpinBox(self.frame)
        self.minFreq.setMinimumSize(QtCore.QSize(75, 0))
        self.minFreq.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.minFreq.setFont(font)
        self.minFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minFreq.setDecimals(1)
        self.minFreq.setMaximum(800.0)
        self.minFreq.setSingleStep(0.1)
        self.minFreq.setObjectName(_fromUtf8("minFreq"))
        self.gridLayout.addWidget(self.minFreq, 15, 3, 1, 1)
        self.soundSpeedButton = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.soundSpeedButton.setFont(font)
        self.soundSpeedButton.setObjectName(_fromUtf8("soundSpeedButton"))
        self.gridLayout.addWidget(self.soundSpeedButton, 2, 5, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 9)
        self.label_11 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 9)
        self.label_4 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 12, 0, 1, 9)
        self.bandFR = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bandFR.setFont(font)
        self.bandFR.setObjectName(_fromUtf8("bandFR"))
        self.gridLayout.addWidget(self.bandFR, 15, 0, 1, 3)
        self.centerFR = QtGui.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.centerFR.setFont(font)
        self.centerFR.setChecked(True)
        self.centerFR.setObjectName(_fromUtf8("centerFR"))
        self.gridLayout.addWidget(self.centerFR, 13, 0, 1, 3)
        self.label_6 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 14, 0, 1, 3)
        self.cFreq = QtGui.QDoubleSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cFreq.setFont(font)
        self.cFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cFreq.setDecimals(1)
        self.cFreq.setMaximum(10000.0)
        self.cFreq.setSingleStep(0.1)
        self.cFreq.setObjectName(_fromUtf8("cFreq"))
        self.gridLayout.addWidget(self.cFreq, 13, 3, 1, 1)
        self.cFreqTau = QtGui.QDoubleSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cFreqTau.setFont(font)
        self.cFreqTau.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cFreqTau.setDecimals(0)
        self.cFreqTau.setMaximum(10000.0)
        self.cFreqTau.setProperty("value", 1024.0)
        self.cFreqTau.setObjectName(_fromUtf8("cFreqTau"))
        self.gridLayout.addWidget(self.cFreqTau, 14, 3, 1, 1)
        self.label_55 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout.addWidget(self.label_55, 13, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 14, 4, 1, 1)
        self.gridLayout_12.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.frame_3 = QtGui.QFrame(self.tab_3)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_37 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_10.addWidget(self.label_37, 2, 0, 1, 5)
        self.label_36 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_10.addWidget(self.label_36, 1, 0, 1, 5)
        self.label_42 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_10.addWidget(self.label_42, 3, 8, 1, 2)
        self.maxFreqBeam = QtGui.QDoubleSpinBox(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.maxFreqBeam.setFont(font)
        self.maxFreqBeam.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxFreqBeam.setDecimals(1)
        self.maxFreqBeam.setMaximum(800.0)
        self.maxFreqBeam.setObjectName(_fromUtf8("maxFreqBeam"))
        self.gridLayout_10.addWidget(self.maxFreqBeam, 1, 5, 1, 3)
        self.label_38 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_10.addWidget(self.label_38, 3, 0, 1, 5)
        self.xducerSizeBeam = QtGui.QDoubleSpinBox(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.xducerSizeBeam.setFont(font)
        self.xducerSizeBeam.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xducerSizeBeam.setMaximum(10000.0)
        self.xducerSizeBeam.setObjectName(_fromUtf8("xducerSizeBeam"))
        self.gridLayout_10.addWidget(self.xducerSizeBeam, 4, 5, 1, 3)
        self.label_39 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_10.addWidget(self.label_39, 4, 0, 1, 5)
        self.xducerSizeUnitBeam = QtGui.QComboBox(self.frame_3)
        self.xducerSizeUnitBeam.setObjectName(_fromUtf8("xducerSizeUnitBeam"))
        self.xducerSizeUnitBeam.addItem(_fromUtf8(""))
        self.xducerSizeUnitBeam.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.xducerSizeUnitBeam, 4, 8, 1, 2)
        self.label_40 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_10.addWidget(self.label_40, 5, 0, 1, 5)
        self.label_35 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_10.addWidget(self.label_35, 0, 0, 1, 5)
        self.minFreqBeam = QtGui.QDoubleSpinBox(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.minFreqBeam.setFont(font)
        self.minFreqBeam.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minFreqBeam.setDecimals(1)
        self.minFreqBeam.setMaximum(800.0)
        self.minFreqBeam.setObjectName(_fromUtf8("minFreqBeam"))
        self.gridLayout_10.addWidget(self.minFreqBeam, 0, 5, 1, 3)
        self.targetRangeBeam = QtGui.QDoubleSpinBox(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.targetRangeBeam.setFont(font)
        self.targetRangeBeam.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetRangeBeam.setMaximum(10000.0)
        self.targetRangeBeam.setObjectName(_fromUtf8("targetRangeBeam"))
        self.gridLayout_10.addWidget(self.targetRangeBeam, 3, 5, 1, 3)
        self.soundSpeedBeam = QtGui.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.soundSpeedBeam.setFont(font)
        self.soundSpeedBeam.setObjectName(_fromUtf8("soundSpeedBeam"))
        self.gridLayout_10.addWidget(self.soundSpeedBeam, 2, 5, 1, 2)
        self.soundSpeedButtonBeam = QtGui.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.soundSpeedButtonBeam.setFont(font)
        self.soundSpeedButtonBeam.setObjectName(_fromUtf8("soundSpeedButtonBeam"))
        self.gridLayout_10.addWidget(self.soundSpeedButtonBeam, 2, 7, 1, 1)
        self.label_41 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_10.addWidget(self.label_41, 2, 8, 1, 2)
        self.label_44 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_10.addWidget(self.label_44, 1, 8, 1, 2)
        self.label_43 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_10.addWidget(self.label_43, 0, 8, 1, 2)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.beamType43 = QtGui.QCheckBox(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.beamType43.setFont(font)
        self.beamType43.setAutoExclusive(True)
        self.beamType43.setObjectName(_fromUtf8("beamType43"))
        self.gridLayout_9.addWidget(self.beamType43, 0, 1, 1, 1)
        self.beamType3 = QtGui.QCheckBox(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.beamType3.setFont(font)
        self.beamType3.setAutoExclusive(True)
        self.beamType3.setObjectName(_fromUtf8("beamType3"))
        self.gridLayout_9.addWidget(self.beamType3, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 5, 5, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout_10, 0, 0, 1, 3)
        self.label_30 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 1, 0, 1, 1)
        self.footprintFreq = QtGui.QDoubleSpinBox(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.footprintFreq.setFont(font)
        self.footprintFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.footprintFreq.setMaximum(1000.0)
        self.footprintFreq.setObjectName(_fromUtf8("footprintFreq"))
        self.gridLayout_2.addWidget(self.footprintFreq, 1, 1, 1, 1)
        self.beamButton = QtGui.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.beamButton.setFont(font)
        self.beamButton.setObjectName(_fromUtf8("beamButton"))
        self.gridLayout_2.addWidget(self.beamButton, 1, 2, 1, 1)
        self.gridLayout_14.addWidget(self.frame_3, 0, 0, 1, 1)
        self.beamFootprintFig = mplwidget(self.tab_3)
        self.beamFootprintFig.setObjectName(_fromUtf8("beamFootprintFig"))
        self.gridLayout_14.addWidget(self.beamFootprintFig, 1, 0, 1, 1)
        self.beamFootprintFig_2 = mplwidget(self.tab_3)
        self.beamFootprintFig_2.setObjectName(_fromUtf8("beamFootprintFig_2"))
        self.gridLayout_14.addWidget(self.beamFootprintFig_2, 2, 0, 1, 1)
        self.beamPatternFig = mplwidget(self.tab_3)
        self.beamPatternFig.setObjectName(_fromUtf8("beamPatternFig"))
        self.gridLayout_14.addWidget(self.beamPatternFig, 0, 1, 3, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_6.addWidget(self.line_3, 0, 1, 3, 2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_3.addWidget(self.label_32, 0, 0, 1, 2)
        self.label_28 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.tempSS = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tempSS.setFont(font)
        self.tempSS.setObjectName(_fromUtf8("tempSS"))
        self.gridLayout_3.addWidget(self.tempSS, 1, 1, 1, 2)
        self.label_22 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 1, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 2, 0, 1, 1)
        self.salinitySS = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.salinitySS.setFont(font)
        self.salinitySS.setObjectName(_fromUtf8("salinitySS"))
        self.gridLayout_3.addWidget(self.salinitySS, 2, 1, 1, 2)
        self.label_23 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_3.addWidget(self.label_23, 2, 3, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_3.addWidget(self.label_24, 3, 0, 1, 1)
        self.depthSS = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.depthSS.setFont(font)
        self.depthSS.setObjectName(_fromUtf8("depthSS"))
        self.gridLayout_3.addWidget(self.depthSS, 3, 1, 1, 2)
        self.label_34 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_3.addWidget(self.label_34, 3, 3, 1, 1)
        self.soundSpeedCalcButton = QtGui.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.soundSpeedCalcButton.setFont(font)
        self.soundSpeedCalcButton.setObjectName(_fromUtf8("soundSpeedCalcButton"))
        self.gridLayout_3.addWidget(self.soundSpeedCalcButton, 4, 0, 1, 2)
        self.soundSpeedResults = QtGui.QLineEdit(self.tab_2)
        self.soundSpeedResults.setObjectName(_fromUtf8("soundSpeedResults"))
        self.gridLayout_3.addWidget(self.soundSpeedResults, 4, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_3.addWidget(self.label_45, 4, 3, 1, 1)
        self.applySSButton = QtGui.QPushButton(self.tab_2)
        self.applySSButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.applySSButton.setFont(font)
        self.applySSButton.setObjectName(_fromUtf8("applySSButton"))
        self.gridLayout_3.addWidget(self.applySSButton, 5, 0, 1, 4)
        self.gridLayout_6.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_33 = QtGui.QLabel(self.tab_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_4.addWidget(self.label_33, 0, 0, 1, 2)
        self.label_53 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_53.setFont(font)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_4.addWidget(self.label_53, 1, 0, 1, 1)
        self.tempAlpha = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tempAlpha.setFont(font)
        self.tempAlpha.setObjectName(_fromUtf8("tempAlpha"))
        self.gridLayout_4.addWidget(self.tempAlpha, 1, 1, 1, 1)
        self.label_51 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_4.addWidget(self.label_51, 1, 2, 1, 1)
        self.line_5 = QtGui.QFrame(self.tab_2)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_4.addWidget(self.line_5, 1, 3, 3, 1)
        self.label_50 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_4.addWidget(self.label_50, 1, 4, 1, 1)
        self.salinityAlpha = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.salinityAlpha.setFont(font)
        self.salinityAlpha.setObjectName(_fromUtf8("salinityAlpha"))
        self.gridLayout_4.addWidget(self.salinityAlpha, 1, 5, 1, 1)
        self.label_47 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_4.addWidget(self.label_47, 1, 6, 1, 1)
        self.label_48 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_4.addWidget(self.label_48, 2, 0, 1, 1)
        self.depthAlpha = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.depthAlpha.setFont(font)
        self.depthAlpha.setObjectName(_fromUtf8("depthAlpha"))
        self.gridLayout_4.addWidget(self.depthAlpha, 2, 1, 1, 1)
        self.label_49 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_4.addWidget(self.label_49, 2, 2, 1, 1)
        self.label_54 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_4.addWidget(self.label_54, 2, 4, 1, 1)
        self.phAlpha = QtGui.QLineEdit(self.tab_2)
        self.phAlpha.setObjectName(_fromUtf8("phAlpha"))
        self.gridLayout_4.addWidget(self.phAlpha, 2, 5, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 2, 6, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_4.addWidget(self.label_31, 3, 0, 1, 1)
        self.soundSpeedAlpha = QtGui.QLineEdit(self.tab_2)
        self.soundSpeedAlpha.setObjectName(_fromUtf8("soundSpeedAlpha"))
        self.gridLayout_4.addWidget(self.soundSpeedAlpha, 3, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_4.addWidget(self.label_46, 3, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 3, 4, 1, 1)
        self.freqAlpha = QtGui.QLineEdit(self.tab_2)
        self.freqAlpha.setObjectName(_fromUtf8("freqAlpha"))
        self.gridLayout_4.addWidget(self.freqAlpha, 3, 5, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_4.addWidget(self.label_29, 3, 6, 1, 1)
        self.alphaResults = QtGui.QLineEdit(self.tab_2)
        self.alphaResults.setObjectName(_fromUtf8("alphaResults"))
        self.gridLayout_4.addWidget(self.alphaResults, 4, 4, 1, 2)
        self.label_52 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_4.addWidget(self.label_52, 4, 6, 1, 1)
        self.alphaCalcButton = QtGui.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.alphaCalcButton.setFont(font)
        self.alphaCalcButton.setObjectName(_fromUtf8("alphaCalcButton"))
        self.gridLayout_4.addWidget(self.alphaCalcButton, 4, 0, 1, 3)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.alphaFig = mplwidget(self.tab_2)
        self.alphaFig.setObjectName(_fromUtf8("alphaFig"))
        self.gridLayout_5.addWidget(self.alphaFig, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 1, 2, 2, 1)
        self.soundSpeedFig = mplwidget(self.tab_2)
        self.soundSpeedFig.setMinimumSize(QtCore.QSize(450, 0))
        self.soundSpeedFig.setObjectName(_fromUtf8("soundSpeedFig"))
        self.gridLayout_6.addWidget(self.soundSpeedFig, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tabWidget, self.waterDensity)
        Form.setTabOrder(self.waterDensity, self.soundSpeed)
        Form.setTabOrder(self.soundSpeed, self.targetMaterial)
        Form.setTabOrder(self.targetMaterial, self.targetDensity)
        Form.setTabOrder(self.targetDensity, self.targetDiameter)
        Form.setTabOrder(self.targetDiameter, self.longSoundSpeed)
        Form.setTabOrder(self.longSoundSpeed, self.tranSoundSpeed)
        Form.setTabOrder(self.tranSoundSpeed, self.calculateTSButton)
        Form.setTabOrder(self.calculateTSButton, self.exportDataButton)
        Form.setTabOrder(self.exportDataButton, self.saveFigButton)
        Form.setTabOrder(self.saveFigButton, self.minFreqBeam)
        Form.setTabOrder(self.minFreqBeam, self.maxFreqBeam)
        Form.setTabOrder(self.maxFreqBeam, self.soundSpeedBeam)
        Form.setTabOrder(self.soundSpeedBeam, self.soundSpeedButtonBeam)
        Form.setTabOrder(self.soundSpeedButtonBeam, self.targetRangeBeam)
        Form.setTabOrder(self.targetRangeBeam, self.xducerSizeBeam)
        Form.setTabOrder(self.xducerSizeBeam, self.xducerSizeUnitBeam)
        Form.setTabOrder(self.xducerSizeUnitBeam, self.beamType3)
        Form.setTabOrder(self.beamType3, self.beamType43)
        Form.setTabOrder(self.beamType43, self.footprintFreq)
        Form.setTabOrder(self.footprintFreq, self.beamButton)
        Form.setTabOrder(self.beamButton, self.tempSS)
        Form.setTabOrder(self.tempSS, self.salinitySS)
        Form.setTabOrder(self.salinitySS, self.depthSS)
        Form.setTabOrder(self.depthSS, self.soundSpeedCalcButton)
        Form.setTabOrder(self.soundSpeedCalcButton, self.soundSpeedResults)
        Form.setTabOrder(self.soundSpeedResults, self.applySSButton)
        Form.setTabOrder(self.applySSButton, self.tempAlpha)
        Form.setTabOrder(self.tempAlpha, self.depthAlpha)
        Form.setTabOrder(self.depthAlpha, self.soundSpeedAlpha)
        Form.setTabOrder(self.soundSpeedAlpha, self.salinityAlpha)
        Form.setTabOrder(self.salinityAlpha, self.phAlpha)
        Form.setTabOrder(self.phAlpha, self.freqAlpha)
        Form.setTabOrder(self.freqAlpha, self.alphaCalcButton)
        Form.setTabOrder(self.alphaCalcButton, self.alphaResults)
        Form.setTabOrder(self.alphaResults, self.beamFootprintFig_2)
        Form.setTabOrder(self.beamFootprintFig_2, self.beamFootprintFig)
        Form.setTabOrder(self.beamFootprintFig, self.TSCurveFigure)
        Form.setTabOrder(self.TSCurveFigure, self.beamPatternFig)
        Form.setTabOrder(self.beamPatternFig, self.alphaFig)
        Form.setTabOrder(self.alphaFig, self.soundSpeedFig)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.calculateTSButton.setText(_translate("Form", "Calculate Target Strength ", None))
        self.saveFigButton.setText(_translate("Form", "Save Figure", None))
        self.exportDataButton.setText(_translate("Form", "Export TS Data", None))
        self.label_10.setText(_translate("Form", "kHz", None))
        self.label_15.setText(_translate("Form", "Target Sound Speed Properties", None))
        self.label_14.setText(_translate("Form", "Target Diameter", None))
        self.label_2.setText(_translate("Form", "Density", None))
        self.targetMaterial.setItemText(0, _translate("Form", "Tungsten-Carbide", None))
        self.targetMaterial.setItemText(1, _translate("Form", "Copper", None))
        self.label_17.setText(_translate("Form", "Transverse", None))
        self.label_16.setText(_translate("Form", "Longitudinal", None))
        self.label_12.setText(_translate("Form", "Target Material", None))
        self.label_13.setText(_translate("Form", "Target Density", None))
        self.label_3.setText(_translate("Form", "Sound Speed", None))
        self.label_5.setText(_translate("Form", "to", None))
        self.label_21.setText(_translate("Form", "m/s", None))
        self.label_20.setText(_translate("Form", "m/s", None))
        self.label_19.setText(_translate("Form", "mm", None))
        self.label_18.setText(_translate("Form", "kg/m3", None))
        self.label_7.setText(_translate("Form", "kg/m3", None))
        self.label_8.setText(_translate("Form", "m/s", None))
        self.soundSpeedButton.setText(_translate("Form", "Calculate", None))
        self.label.setText(_translate("Form", "Water Properties", None))
        self.label_11.setText(_translate("Form", "Target Properties", None))
        self.label_4.setText(_translate("Form", "Frequency Response", None))
        self.bandFR.setText(_translate("Form", "Bandwidth", None))
        self.centerFR.setText(_translate("Form", "Center Frequency", None))
        self.label_6.setText(_translate("Form", "    Pulse Duration", None))
        self.label_55.setText(_translate("Form", "kHz", None))
        self.label_9.setText(_translate("Form", "µs", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Target Strength Curve", None))
        self.label_37.setText(_translate("Form", "Sound Speed", None))
        self.label_36.setText(_translate("Form", "Maximum Frequency", None))
        self.label_42.setText(_translate("Form", "meters", None))
        self.label_38.setText(_translate("Form", "Range of Interest", None))
        self.label_39.setText(_translate("Form", "Transducer Diameter", None))
        self.xducerSizeUnitBeam.setItemText(0, _translate("Form", "cm", None))
        self.xducerSizeUnitBeam.setItemText(1, _translate("Form", "in", None))
        self.label_40.setText(_translate("Form", "Beam Type", None))
        self.label_35.setText(_translate("Form", "Minimum Frequency", None))
        self.soundSpeedButtonBeam.setText(_translate("Form", "Calculate", None))
        self.label_41.setText(_translate("Form", "m/s", None))
        self.label_44.setText(_translate("Form", "kHz", None))
        self.label_43.setText(_translate("Form", "kHz", None))
        self.beamType43.setText(_translate("Form", "-4.3 dB", None))
        self.beamType3.setText(_translate("Form", "-3 dB", None))
        self.label_30.setText(_translate("Form", "Frequency for Footprint", None))
        self.beamButton.setText(_translate("Form", "Calculate Beam", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Beamwidth Footprints", None))
        self.label_32.setText(_translate("Form", "Calculate Sound Speed", None))
        self.label_28.setText(_translate("Form", "Temperature", None))
        self.label_22.setText(_translate("Form", "ºC", None))
        self.label_27.setText(_translate("Form", "Salinity", None))
        self.label_23.setText(_translate("Form", "psu", None))
        self.label_24.setText(_translate("Form", "Depth", None))
        self.label_34.setText(_translate("Form", "meters", None))
        self.soundSpeedCalcButton.setText(_translate("Form", "Calculate Sound Speed", None))
        self.label_45.setText(_translate("Form", "m/s", None))
        self.applySSButton.setText(_translate("Form", "Apply to Calculations", None))
        self.label_33.setText(_translate("Form", "Calculate Attentuation Coefficient", None))
        self.label_53.setText(_translate("Form", "Temperature", None))
        self.label_51.setText(_translate("Form", "ºC", None))
        self.label_50.setText(_translate("Form", "Salinity", None))
        self.label_47.setText(_translate("Form", "psu", None))
        self.label_48.setText(_translate("Form", "Depth", None))
        self.label_49.setText(_translate("Form", "meters", None))
        self.label_54.setText(_translate("Form", "Acidity", None))
        self.label_26.setText(_translate("Form", "pH", None))
        self.label_31.setText(_translate("Form", "Sound Speed", None))
        self.label_46.setText(_translate("Form", "m/s", None))
        self.label_25.setText(_translate("Form", "Frequency", None))
        self.label_29.setText(_translate("Form", "kHz", None))
        self.label_52.setText(_translate("Form", "dB/km", None))
        self.alphaCalcButton.setText(_translate("Form", "Calculate Attentuation Coefficient", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Sound Speed and Attenuation Coefficient Calculator", None))

from mplwidget import mplwidget
