# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TargetStrength3.ui'
#
# Created: Tue Oct 14 13:28:19 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(544, 706)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Calculate_but = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Calculate_but.setFont(font)
        self.Calculate_but.setObjectName(_fromUtf8("Calculate_but"))
        self.gridLayout_2.addWidget(self.Calculate_but, 1, 1, 1, 2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 6, 2, 1, 1)
        self.max_freq = QtGui.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.max_freq.setFont(font)
        self.max_freq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.max_freq.setMaximum(100000)
        self.max_freq.setObjectName(_fromUtf8("max_freq"))
        self.gridLayout.addWidget(self.max_freq, 6, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 5, 6, 1, 1)
        self.target_ts_long = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.target_ts_long.setFont(font)
        self.target_ts_long.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.target_ts_long.setObjectName(_fromUtf8("target_ts_long"))
        self.gridLayout.addWidget(self.target_ts_long, 5, 5, 1, 1)
        self.water_density = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.water_density.setFont(font)
        self.water_density.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.water_density.setObjectName(_fromUtf8("water_density"))
        self.gridLayout.addWidget(self.water_density, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 5, 4, 1, 1)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 6, 6, 1, 1)
        self.label_18 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 6, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 4, 0, 1, 3)
        self.target_ts_trans = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.target_ts_trans.setFont(font)
        self.target_ts_trans.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.target_ts_trans.setObjectName(_fromUtf8("target_ts_trans"))
        self.gridLayout.addWidget(self.target_ts_trans, 6, 5, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 3, 6, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 6, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 3)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 4, 4, 1, 3)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 0, 4, 1, 3)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 1, 4, 1, 1)
        self.target_diameter = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.target_diameter.setFont(font)
        self.target_diameter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.target_diameter.setObjectName(_fromUtf8("target_diameter"))
        self.gridLayout.addWidget(self.target_diameter, 3, 5, 1, 1)
        self.target_material = QtGui.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.target_material.setFont(font)
        self.target_material.setObjectName(_fromUtf8("target_material"))
        self.target_material.addItem(_fromUtf8(""))
        self.target_material.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.target_material, 1, 5, 1, 2)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 4, 1, 1)
        self.water_soundspeed = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.water_soundspeed.setFont(font)
        self.water_soundspeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.water_soundspeed.setObjectName(_fromUtf8("water_soundspeed"))
        self.gridLayout.addWidget(self.water_soundspeed, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 2, 6, 1, 1)
        self.target_density = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.target_density.setFont(font)
        self.target_density.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.target_density.setObjectName(_fromUtf8("target_density"))
        self.gridLayout.addWidget(self.target_density, 2, 5, 1, 1)
        self.label_20 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 2, 4, 1, 1)
        self.min_freq = QtGui.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.min_freq.setFont(font)
        self.min_freq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.min_freq.setMaximum(100000)
        self.min_freq.setObjectName(_fromUtf8("min_freq"))
        self.gridLayout.addWidget(self.min_freq, 5, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 3, 1, 1)
        self.save_fig_but = QtGui.QPushButton(self.centralwidget)
        self.save_fig_but.setMaximumSize(QtCore.QSize(120, 16777215))
        self.save_fig_but.setObjectName(_fromUtf8("save_fig_but"))
        self.gridLayout_2.addWidget(self.save_fig_but, 3, 2, 1, 1)
        self.widget = mplwidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2.addWidget(self.widget, 2, 1, 1, 2)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 544, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.water_density, self.water_soundspeed)
        mainWindow.setTabOrder(self.water_soundspeed, self.min_freq)
        mainWindow.setTabOrder(self.min_freq, self.max_freq)
        mainWindow.setTabOrder(self.max_freq, self.target_material)
        mainWindow.setTabOrder(self.target_material, self.target_density)
        mainWindow.setTabOrder(self.target_density, self.target_diameter)
        mainWindow.setTabOrder(self.target_diameter, self.target_ts_long)
        mainWindow.setTabOrder(self.target_ts_long, self.target_ts_trans)
        mainWindow.setTabOrder(self.target_ts_trans, self.Calculate_but)
        mainWindow.setTabOrder(self.Calculate_but, self.widget)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Target Strength of Standard Target", None))
        self.Calculate_but.setText(_translate("mainWindow", "Calculate Target Strength Curve", None))
        self.label_8.setText(_translate("mainWindow", "kHz", None))
        self.label_10.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">kg/m</span><span style=\" font-size:10pt; vertical-align:super;\">3</span></p></body></html>", None))
        self.label.setText(_translate("mainWindow", "<html><head/><body><p>Density</p></body></html>", None))
        self.label_14.setText(_translate("mainWindow", "m/s", None))
        self.target_ts_long.setText(_translate("mainWindow", "6853", None))
        self.label_3.setText(_translate("mainWindow", "Longitudinal", None))
        self.label_15.setText(_translate("mainWindow", "m/s", None))
        self.label_18.setText(_translate("mainWindow", "Max. Frequency", None))
        self.label_19.setText(_translate("mainWindow", "Target Strength Curve", None))
        self.target_ts_trans.setText(_translate("mainWindow", "4171", None))
        self.label_5.setText(_translate("mainWindow", "kHz", None))
        self.label_17.setText(_translate("mainWindow", "mm", None))
        self.label_4.setText(_translate("mainWindow", "Transverse", None))
        self.label_9.setText(_translate("mainWindow", "Water Properties", None))
        self.label_16.setText(_translate("mainWindow", "Target Sound Speed", None))
        self.label_13.setText(_translate("mainWindow", "Target Properties", None))
        self.label_7.setText(_translate("mainWindow", "Min. Frequency", None))
        self.label_12.setText(_translate("mainWindow", "Target Material", None))
        self.target_diameter.setText(_translate("mainWindow", "38.1", None))
        self.target_material.setItemText(0, _translate("mainWindow", "Tungsten-Carbide", None))
        self.target_material.setItemText(1, _translate("mainWindow", "Copper", None))
        self.label_6.setText(_translate("mainWindow", "Target Diameter", None))
        self.label_2.setText(_translate("mainWindow", "Sound Speed", None))
        self.label_11.setText(_translate("mainWindow", "m/s", None))
        self.label_21.setText(_translate("mainWindow", "<html><head/><body><p>kg/m<span style=\" vertical-align:super;\">3</span></p></body></html>", None))
        self.target_density.setText(_translate("mainWindow", "14900", None))
        self.label_20.setText(_translate("mainWindow", "Target Density", None))
        self.save_fig_but.setText(_translate("mainWindow", "Save Figure", None))

from mplwidget import mplwidget